### ISSUE TITLE
Null Pointer Error when using setImageBitmap for ImageView

### ISSUE THREAD

**Issue by madhall** [tejpratap46/PDFCreatorAndroid#30]
Hi,

I am trying to display an image from the gallery using Mediastore but when I run the below code, the pdf doesnt launch but crashes with an error saying below. Can you please guide? It is the only issue with launching this feature... inability to display image from gallery on pdf.
```
   java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter exception
        at in.trial.trial.Invoicing.ui.downloadInvoicePdf$onCreate$1.pdfGenerationFailure(Unknown Source:2)
        at com.tejpratapsingh.pdfcreator.activity.PDFCreatorActivity$1.pdfGenerationFailure(PDFCreatorActivity.java:128)
        at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.onPostExecute(PDFUtil.java:192)
        at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.onPostExecute(PDFUtil.java:129)
```
```kotlin
if(user.logoUrl != null){
    val uri = user.logoUrl!!.toUri()
    try {
            if(Build.VERSION.SDK_INT < 28) {
                bitmap = MediaStore.Images.Media.getBitmap(
                    this.contentResolver,
                    uri
                )
            } else {
                val source = ImageDecoder.createSource(this.contentResolver, uri)
                bitmap = ImageDecoder.decodeBitmap(source)
            }
    } catch (e: Exception) {
        e.printStackTrace()
    }
    Log.i("Link", bitmap.toString())
    imageView.setImageBitmap(bitmap)
    imageLayoutParam.setMargins(0, 0, 10, 10)
    imageView.setLayout(imageLayoutParam)
    horizontalView.addView(imageView)
}
```

**Comment by tejpratap46** [comment]
After reading logs, it looks like you are passing null to a non-null parameter.

Option 1:
- Try to set your bitmap to a image in your activity.
- Check you code for null issues, if still facing issue, post full log.

**Comment by madhall** [comment]
Hi Tej,

Yes, I am facing an issue on this line of code:

 imageView.setImageBitmap(bitmap)

When I comment it out, the pdf is generated without an Image. I am unable to print image from the activity as I am launching PDF on button click. The bitmap being sent across is below:

2021-06-29 09:57:43.603 16113-16113/in.trial.trial I/Link: android.graphics.Bitmap@92da342
2021-06-29 09:57:43.610 16113-16113/in.trial.trial I/Link: android.graphics.Bitmap@5f70daf

This seems to be the issue:

**Software rendering doesn't support hardware bitmaps**

Used a Log.i check if the Bitmap value is null. Below is the error Log, what do you suggest? thanks for your help

```
731 16113-16357/in.trial.trial W/System.err: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
2021-06-29 09:57:43.732 16113-16197/in.trial.trial D/FA: Connected to remote service
2021-06-29 09:57:43.733 16113-16197/in.trial.trial V/FA: Processing queued up service tasks: 4
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.MiuiCanvas.throwIfCannotDraw(MiuiCanvas.java:329)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:131)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.MiuiCanvas.drawBitmap(MiuiCanvas.java:110)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.Canvas.drawBitmap(Canvas.java:1601)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
2021-06-29 09:57:43.734 16113-16357/iin.trial.trial W/System.err:     at android.widget.ImageView.onDraw(ImageView.java:1434)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21551)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21422)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21420)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21420)
2021-06-29 09:57:43.734 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
2021-06-29 09:57:43.734 16113-16357/in.trial.trialW/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21420)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.view.View.draw(View.java:21554)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.writePDFDocument(PDFUtil.java:224)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.doInBackground(PDFUtil.java:169)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.doInBackground(PDFUtil.java:129)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-06-29 09:57:43.735 16113-16357/in.trial.trial W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-06-29 09:57:43.744 16113-16113/in.trial.trial D/AndroidRuntime: Shutting down VM
`2021-06-29 09:57:43.744 16113-16113/in.trial.trial E/AndroidRuntime: FATAL EXCEPTION: main
```
   
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter exception
        at in.trial.trial.Invoicing.ui.downloadInvoicePdf$onCreate$1.pdfGenerationFailure(Unknown Source:2)
        at com.tejpratapsingh.pdfcreator.activity.PDFCreatorActivity$1.pdfGenerationFailure(PDFCreatorActivity.java:128)
        at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.onPostExecute(PDFUtil.java:192)
        at com.tejpratapsingh.pdfcreator.utils.PDFUtil$GeneratePDFAsync.onPostExecute(PDFUtil.java:129)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by tejpratap46** [comment]
Sorry, I do not have time for this issue now, as I would have to implement a file picker of my own and test this iisue. will test it as soon as I get time.

What you can do is (and this is what we usually do to test a image):
Save that bitmap to you app's private storage using below code,
```java
FileManager.getInstance().saveImageToFile()
```
https://github.com/tejpratap46/PDFCreatorAndroid/blob/04401cfcb77b23aeaff49e3c8ebcb94521aa254d/pdfcreator/src/main/java/com/tejpratapsingh/pdfcreator/utils/FileManager.java#L442

And open your apps private files using an external File Explorer App. (Which is usually inside `Android->data->[Your Package Name]`) and if saved image is all right (Has size, can be opened via image viewer etc.)

And if saved image is fine, then you can use `pdfImageView.setImageFile()` to render image in pdf
https://github.com/tejpratap46/PDFCreatorAndroid/blob/04401cfcb77b23aeaff49e3c8ebcb94521aa254d/pdfcreator/src/main/java/com/tejpratapsingh/pdfcreator/views/basic/PDFImageView.java#L46

**Comment by madhall** [comment]
Thanks for looking into this! Will try this out, cheers

Please close the issue if you would like to!
