### ISSUE TITLE
NullPointer exception Click on next

### ISSUE THREAD

**Issue by zpluscybersecuretech** [tejpratap46/PDFCreatorAndroid#31]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sit.a22junpdftestapplication, PID: 12173
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sit.a22junpdftestapplication/com.sit.a22junpdftestapplication.PdfViewerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tejpratapsingh.pdfcreator.custom.ViewPagerForPhotoView.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tejpratapsingh.pdfcreator.custom.ViewPagerForPhotoView.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
        at com.tejpratapsingh.pdfcreator.activity.PDFViewerActivity.onCreate(PDFViewerActivity.java:71)
        at com.sit.a22junpdftestapplication.PdfViewerActivity.onCreate(PdfViewerActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by zpluscybersecuretech** [comment]
@Override
    protected void onNextClicked(File savedPDFFile) {
        Uri pdfUri = Uri.fromFile(savedPDFFile);

        Intent intentPdfViewer = new Intent(PdfCreatorActivity.this, PdfViewerActivity.class);
        intentPdfViewer.putExtra(PdfViewerActivity.PDF_FILE_URI, pdfUri);

        startActivity(intentPdfViewer);
    }

**Comment by zpluscybersecuretech** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.sit.a22junpdftestapplication, PID: 12173
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sit.a22junpdftestapplication/com.sit.a22junpdftestapplication.PdfViewerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tejpratapsingh.pdfcreator.custom.ViewPagerForPhotoView.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:201)
> at android.app.ActivityThread.main(ActivityThread.java:6810)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tejpratapsingh.pdfcreator.custom.ViewPagerForPhotoView.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
> at com.tejpratapsingh.pdfcreator.activity.PDFViewerActivity.onCreate(PDFViewerActivity.java:71)
> at com.sit.a22junpdftestapplication.PdfViewerActivity.onCreate(PdfViewerActivity.java:25)
> at android.app.Activity.performCreate(Activity.java:7224)
> at android.app.Activity.performCreate(Activity.java:7213)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
> at android.os.Handler.dispatchMessage(Handler.java:106) 
> at android.os.Looper.loop(Looper.java:201) 
> at android.app.ActivityThread.main(ActivityThread.java:6810) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

@override
protected void onNextClicked(File savedPDFFile) {
Uri pdfUri = Uri.fromFile(savedPDFFile);

    Intent intentPdfViewer = new Intent(PdfCreatorActivity.this, PdfViewerActivity.class);
    intentPdfViewer.putExtra(PdfViewerActivity.PDF_FILE_URI, pdfUri);

    startActivity(intentPdfViewer);
}
