### ISSUE TITLE
Android 12 Fatal Exception: java.lang.IllegalArgumentException: fd cannot be null

### ISSUE THREAD

**Issue by mujahid-dzinemedia** [tejpratap46/PDFCreatorAndroid#55]
`Fatal Exception: java.lang.IllegalArgumentException: fd cannot be null
       at ub.onWrite(chromium-TrichromeWebViewGoogle.aab-stable-556311633:187)
       at android.print.PDFPrint$2.onLayoutFinished(PDFPrint.java:73)
       at ub.onLayout(chromium-TrichromeWebViewGoogle.aab-stable-556311633:15)
       at android.print.PDFPrint.generatePDFFromWebView(PDFPrint.java:70)
       at com.tejpratapsingh.pdfcreator.utils.PDFUtil.generatePDFFromWebView(PDFUtil.java:74)`

**Comment by mujahid-dzinemedia** [comment]
version added

**Comment by issacNabil** [comment]
+1

**Comment by mujahid-dzinemedia** [comment]
@tejpratap46 Please help
